"""added death_faction to games model

Revision ID: 47ec445f7623
Revises: ebb34bef2595
Create Date: 2023-03-27 14:36:19.564375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ec445f7623'
down_revision = 'ebb34bef2595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('death_faction', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('death_faction')

    # ### end Alembic commands ###
