"""added friends list

Revision ID: 4d1cc8391b2e
Revises: 4713f6b54dd3
Create Date: 2023-03-01 15:05:48.856997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1cc8391b2e'
down_revision = '4713f6b54dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('friend_a_id', sa.Integer(), nullable=False),
    sa.Column('friend_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['friend_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('friend_a_id', 'friend_b_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    # ### end Alembic commands ###
