"""added generic villagers and evos to games model

Revision ID: 71cc2005f52d
Revises: b53861fa9450
Create Date: 2023-03-02 16:31:04.916173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cc2005f52d'
down_revision = 'b53861fa9450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('villager_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('villager_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('villager_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('villager_4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('villager_5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('villager_1_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('villager_2_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('villager_3_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('villager_4_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('villager_5_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('evos_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evos_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evos_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evos_4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evos_1_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('evos_2_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('evos_3_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('evos_4_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('evos_4_status')
        batch_op.drop_column('evos_3_status')
        batch_op.drop_column('evos_2_status')
        batch_op.drop_column('evos_1_status')
        batch_op.drop_column('evos_4')
        batch_op.drop_column('evos_3')
        batch_op.drop_column('evos_2')
        batch_op.drop_column('evos_1')
        batch_op.drop_column('villager_5_status')
        batch_op.drop_column('villager_4_status')
        batch_op.drop_column('villager_3_status')
        batch_op.drop_column('villager_2_status')
        batch_op.drop_column('villager_1_status')
        batch_op.drop_column('villager_5')
        batch_op.drop_column('villager_4')
        batch_op.drop_column('villager_3')
        batch_op.drop_column('villager_2')
        batch_op.drop_column('villager_1')

    # ### end Alembic commands ###
