"""created games model

Revision ID: 907826446c7f
Revises: 4d1cc8391b2e
Create Date: 2023-03-02 13:46:42.424113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907826446c7f'
down_revision = '4d1cc8391b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_players', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('death', sa.Integer(), nullable=True),
    sa.Column('time_shifter', sa.Integer(), nullable=True),
    sa.Column('cultist', sa.Integer(), nullable=True),
    sa.Column('necromancer', sa.Integer(), nullable=True),
    sa.Column('disruptor', sa.Integer(), nullable=True),
    sa.Column('psychic', sa.Integer(), nullable=True),
    sa.Column('jesus', sa.Integer(), nullable=True),
    sa.Column('medium', sa.Integer(), nullable=True),
    sa.Column('mystic', sa.Integer(), nullable=True),
    sa.Column('antideath', sa.Integer(), nullable=True),
    sa.Column('death_status', sa.String(length=50), nullable=True),
    sa.Column('time_shifter_status', sa.String(length=50), nullable=True),
    sa.Column('cultist_status', sa.String(length=50), nullable=True),
    sa.Column('necromancer_status', sa.String(length=50), nullable=True),
    sa.Column('disruptor_status', sa.String(length=50), nullable=True),
    sa.Column('psychic_status', sa.String(length=50), nullable=True),
    sa.Column('jesus_status', sa.String(length=50), nullable=True),
    sa.Column('medium_status', sa.String(length=50), nullable=True),
    sa.Column('mystic_status', sa.String(length=50), nullable=True),
    sa.Column('antideath_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['antideath'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cultist'], ['users.id'], ),
    sa.ForeignKeyConstraint(['death'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disruptor'], ['users.id'], ),
    sa.ForeignKeyConstraint(['jesus'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medium'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mystic'], ['users.id'], ),
    sa.ForeignKeyConstraint(['necromancer'], ['users.id'], ),
    sa.ForeignKeyConstraint(['psychic'], ['users.id'], ),
    sa.ForeignKeyConstraint(['time_shifter'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
