"""made inviter_id no longer a foreign key on gameinvite table

Revision ID: cf49d332d388
Revises: ef7d6f9dff3d
Create Date: 2023-03-02 18:08:58.324580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf49d332d388'
down_revision = 'ef7d6f9dff3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_invites', schema=None) as batch_op:
        batch_op.drop_constraint('game_invites_inviter_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_invites', schema=None) as batch_op:
        batch_op.create_foreign_key('game_invites_inviter_id_fkey', 'users', ['inviter_id'], ['id'])

    # ### end Alembic commands ###
