"""added default factions to games model

Revision ID: d401dada6b47
Revises: 47ec445f7623
Create Date: 2023-03-28 16:38:36.384124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd401dada6b47'
down_revision = '47ec445f7623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_shifter_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cultist_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('necromancer_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('disruptor_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('psychic_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('jesus_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('medium_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mystic_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('antideath_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('villager_1_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('villager_2_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('villager_3_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('villager_4_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('villager_5_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('evos_1_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('evos_2_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('evos_3_faction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('evos_4_faction', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('evos_4_faction')
        batch_op.drop_column('evos_3_faction')
        batch_op.drop_column('evos_2_faction')
        batch_op.drop_column('evos_1_faction')
        batch_op.drop_column('villager_5_faction')
        batch_op.drop_column('villager_4_faction')
        batch_op.drop_column('villager_3_faction')
        batch_op.drop_column('villager_2_faction')
        batch_op.drop_column('villager_1_faction')
        batch_op.drop_column('antideath_faction')
        batch_op.drop_column('mystic_faction')
        batch_op.drop_column('medium_faction')
        batch_op.drop_column('jesus_faction')
        batch_op.drop_column('psychic_faction')
        batch_op.drop_column('disruptor_faction')
        batch_op.drop_column('necromancer_faction')
        batch_op.drop_column('cultist_faction')
        batch_op.drop_column('time_shifter_faction')

    # ### end Alembic commands ###
