"""changed winner default value to "none"

Revision ID: d8815298f47b
Revises: ddb0a862b9bb
Create Date: 2023-04-05 14:39:56.867242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8815298f47b'
down_revision = 'ddb0a862b9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.String(length=50), default='none', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('winner')

    # ### end Alembic commands ###
