"""added caller_name and marked_name to marks

Revision ID: ddb0a862b9bb
Revises: 57142e224cb6
Create Date: 2023-03-30 16:50:08.945522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb0a862b9bb'
down_revision = '57142e224cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caller_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('marked_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.drop_column('marked_name')
        batch_op.drop_column('caller_name')

    # ### end Alembic commands ###
